/**
 * Region-to-Discord-role mapping and country-to-region lookup.
 * Used during onboarding to assign a regional Discord role based on the user's city.
 */

// ============================================================================
// Region Discord Role IDs
// ============================================================================

export const REGION_ROLE_IDS: Record<string, string> = {
  NORTH_AMERICA: "1255532546767454260",
  CENTRAL_AMERICA: "1256266615402664109",
  SOUTH_AMERICA: "1255532930420310077",
  WESTERN_EUROPE: "1255531586779091055",
  EASTERN_EUROPE: "1256266998221111408",
  AFRICA: "1255532098509340723",
  MIDDLE_EAST: "1256266858646995064",
  ASIA: "1255532251496583178",
  OCEANIA: "1255532710412288121",
};

/** Set of all region role IDs, used to strip old region roles before assigning a new one. */
export const ALL_REGION_ROLE_IDS = new Set(Object.values(REGION_ROLE_IDS));

// ============================================================================
// Country Code -> Region Lookup (ISO 3166-1 alpha-2)
// ============================================================================

export const COUNTRY_TO_REGION: Record<string, string> = {
  // --- NORTH AMERICA ---
  US: "NORTH_AMERICA",
  CA: "NORTH_AMERICA",

  // --- CENTRAL AMERICA & CARIBBEAN ---
  MX: "CENTRAL_AMERICA",
  GT: "CENTRAL_AMERICA",
  BZ: "CENTRAL_AMERICA",
  HN: "CENTRAL_AMERICA",
  SV: "CENTRAL_AMERICA",
  NI: "CENTRAL_AMERICA",
  CR: "CENTRAL_AMERICA",
  PA: "CENTRAL_AMERICA",
  CU: "CENTRAL_AMERICA",
  JM: "CENTRAL_AMERICA",
  HT: "CENTRAL_AMERICA",
  DO: "CENTRAL_AMERICA",
  TT: "CENTRAL_AMERICA",
  BS: "CENTRAL_AMERICA",
  BB: "CENTRAL_AMERICA",
  AG: "CENTRAL_AMERICA",
  DM: "CENTRAL_AMERICA",
  GD: "CENTRAL_AMERICA",
  KN: "CENTRAL_AMERICA",
  LC: "CENTRAL_AMERICA",
  VC: "CENTRAL_AMERICA",
  PR: "CENTRAL_AMERICA",
  VI: "CENTRAL_AMERICA",
  VG: "CENTRAL_AMERICA",
  AI: "CENTRAL_AMERICA",
  MS: "CENTRAL_AMERICA",
  KY: "CENTRAL_AMERICA",
  TC: "CENTRAL_AMERICA",
  AW: "CENTRAL_AMERICA",
  CW: "CENTRAL_AMERICA",
  SX: "CENTRAL_AMERICA",
  BQ: "CENTRAL_AMERICA",
  BL: "CENTRAL_AMERICA",
  MF: "CENTRAL_AMERICA",
  GP: "CENTRAL_AMERICA",
  MQ: "CENTRAL_AMERICA",

  // --- SOUTH AMERICA ---
  BR: "SOUTH_AMERICA",
  AR: "SOUTH_AMERICA",
  CL: "SOUTH_AMERICA",
  CO: "SOUTH_AMERICA",
  PE: "SOUTH_AMERICA",
  VE: "SOUTH_AMERICA",
  EC: "SOUTH_AMERICA",
  BO: "SOUTH_AMERICA",
  PY: "SOUTH_AMERICA",
  UY: "SOUTH_AMERICA",
  GY: "SOUTH_AMERICA",
  SR: "SOUTH_AMERICA",
  GF: "SOUTH_AMERICA",
  FK: "SOUTH_AMERICA",

  // --- WESTERN EUROPE ---
  GB: "WESTERN_EUROPE",
  FR: "WESTERN_EUROPE",
  DE: "WESTERN_EUROPE",
  IT: "WESTERN_EUROPE",
  ES: "WESTERN_EUROPE",
  PT: "WESTERN_EUROPE",
  NL: "WESTERN_EUROPE",
  BE: "WESTERN_EUROPE",
  AT: "WESTERN_EUROPE",
  CH: "WESTERN_EUROPE",
  IE: "WESTERN_EUROPE",
  LU: "WESTERN_EUROPE",
  MC: "WESTERN_EUROPE",
  AD: "WESTERN_EUROPE",
  LI: "WESTERN_EUROPE",
  MT: "WESTERN_EUROPE",
  SM: "WESTERN_EUROPE",
  VA: "WESTERN_EUROPE",
  IS: "WESTERN_EUROPE",
  NO: "WESTERN_EUROPE",
  SE: "WESTERN_EUROPE",
  DK: "WESTERN_EUROPE",
  FI: "WESTERN_EUROPE",
  GI: "WESTERN_EUROPE",
  JE: "WESTERN_EUROPE",
  GG: "WESTERN_EUROPE",
  IM: "WESTERN_EUROPE",
  FO: "WESTERN_EUROPE",
  GL: "WESTERN_EUROPE",
  AX: "WESTERN_EUROPE",
  SJ: "WESTERN_EUROPE",

  // --- EASTERN EUROPE ---
  PL: "EASTERN_EUROPE",
  CZ: "EASTERN_EUROPE",
  SK: "EASTERN_EUROPE",
  HU: "EASTERN_EUROPE",
  RO: "EASTERN_EUROPE",
  BG: "EASTERN_EUROPE",
  HR: "EASTERN_EUROPE",
  SI: "EASTERN_EUROPE",
  RS: "EASTERN_EUROPE",
  BA: "EASTERN_EUROPE",
  ME: "EASTERN_EUROPE",
  MK: "EASTERN_EUROPE",
  AL: "EASTERN_EUROPE",
  XK: "EASTERN_EUROPE",
  UA: "EASTERN_EUROPE",
  BY: "EASTERN_EUROPE",
  MD: "EASTERN_EUROPE",
  LT: "EASTERN_EUROPE",
  LV: "EASTERN_EUROPE",
  EE: "EASTERN_EUROPE",
  GE: "EASTERN_EUROPE",
  AM: "EASTERN_EUROPE",
  AZ: "EASTERN_EUROPE",
  RU: "EASTERN_EUROPE",

  // --- AFRICA ---
  DZ: "AFRICA",
  AO: "AFRICA",
  BJ: "AFRICA",
  BW: "AFRICA",
  BF: "AFRICA",
  BI: "AFRICA",
  CV: "AFRICA",
  CM: "AFRICA",
  CF: "AFRICA",
  TD: "AFRICA",
  KM: "AFRICA",
  CG: "AFRICA",
  CD: "AFRICA",
  DJ: "AFRICA",
  EG: "AFRICA",
  GQ: "AFRICA",
  ER: "AFRICA",
  SZ: "AFRICA",
  ET: "AFRICA",
  GA: "AFRICA",
  GM: "AFRICA",
  GH: "AFRICA",
  GN: "AFRICA",
  GW: "AFRICA",
  CI: "AFRICA",
  KE: "AFRICA",
  LS: "AFRICA",
  LR: "AFRICA",
  LY: "AFRICA",
  MG: "AFRICA",
  MW: "AFRICA",
  ML: "AFRICA",
  MR: "AFRICA",
  MU: "AFRICA",
  YT: "AFRICA",
  MA: "AFRICA",
  MZ: "AFRICA",
  NA: "AFRICA",
  NE: "AFRICA",
  NG: "AFRICA",
  RE: "AFRICA",
  RW: "AFRICA",
  ST: "AFRICA",
  SN: "AFRICA",
  SC: "AFRICA",
  SL: "AFRICA",
  SO: "AFRICA",
  ZA: "AFRICA",
  SS: "AFRICA",
  SD: "AFRICA",
  TZ: "AFRICA",
  TG: "AFRICA",
  TN: "AFRICA",
  UG: "AFRICA",
  ZM: "AFRICA",
  ZW: "AFRICA",
  EH: "AFRICA",
  SH: "AFRICA",
  IO: "AFRICA",

  // --- MIDDLE EAST ---
  SA: "MIDDLE_EAST",
  AE: "MIDDLE_EAST",
  QA: "MIDDLE_EAST",
  KW: "MIDDLE_EAST",
  BH: "MIDDLE_EAST",
  OM: "MIDDLE_EAST",
  IQ: "MIDDLE_EAST",
  IR: "MIDDLE_EAST",
  SY: "MIDDLE_EAST",
  JO: "MIDDLE_EAST",
  LB: "MIDDLE_EAST",
  IL: "MIDDLE_EAST",
  PS: "MIDDLE_EAST",
  YE: "MIDDLE_EAST",
  TR: "MIDDLE_EAST",
  CY: "MIDDLE_EAST",

  // --- ASIA ---
  AF: "ASIA",
  BD: "ASIA",
  BT: "ASIA",
  BN: "ASIA",
  KH: "ASIA",
  CN: "ASIA",
  TL: "ASIA",
  IN: "ASIA",
  ID: "ASIA",
  JP: "ASIA",
  KZ: "ASIA",
  KG: "ASIA",
  LA: "ASIA",
  MY: "ASIA",
  MV: "ASIA",
  MN: "ASIA",
  MM: "ASIA",
  NP: "ASIA",
  KP: "ASIA",
  KR: "ASIA",
  PK: "ASIA",
  PH: "ASIA",
  SG: "ASIA",
  LK: "ASIA",
  TW: "ASIA",
  TJ: "ASIA",
  TH: "ASIA",
  TM: "ASIA",
  UZ: "ASIA",
  VN: "ASIA",
  HK: "ASIA",
  MO: "ASIA",

  // --- OCEANIA ---
  AU: "OCEANIA",
  NZ: "OCEANIA",
  FJ: "OCEANIA",
  PG: "OCEANIA",
  WS: "OCEANIA",
  TO: "OCEANIA",
  VU: "OCEANIA",
  SB: "OCEANIA",
  KI: "OCEANIA",
  MH: "OCEANIA",
  FM: "OCEANIA",
  PW: "OCEANIA",
  TV: "OCEANIA",
  NR: "OCEANIA",
  CK: "OCEANIA",
  NU: "OCEANIA",
  TK: "OCEANIA",
  AS: "OCEANIA",
  GU: "OCEANIA",
  MP: "OCEANIA",
  NC: "OCEANIA",
  PF: "OCEANIA",
  WF: "OCEANIA",
  PN: "OCEANIA",
  NF: "OCEANIA",
  CC: "OCEANIA",
  CX: "OCEANIA",
  HM: "OCEANIA",
};

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Resolve an ISO 3166-1 alpha-2 country code to a region key.
 * Returns null if the code is not recognized.
 */
export function resolveRegionFromCountryCode(code: string): string | null {
  if (!code) return null;
  return COUNTRY_TO_REGION[code.toUpperCase().trim()] ?? null;
}

/**
 * Get the Discord role ID for a region key (e.g. "NORTH_AMERICA").
 * Returns null if the region key is not recognized.
 */
export function getRegionRoleId(regionKey: string): string | null {
  if (!regionKey) return null;
  return REGION_ROLE_IDS[regionKey.toUpperCase().trim()] ?? null;
}
