#!/usr/bin/env node
// e2e/local/run.mjs — `npm run e2e:local`
//
// Logged-in smoke test against a fully local setup:
//   1. starts a throwaway Postgres (docker, tmpfs; or E2E_DATABASE_URL on localhost)
//   2. creates the schema (prisma db push) and seeds synthetic test members
//   3. mints session cookies with the app's own signer (app/lib/session.ts)
//   4. runs e2e/logged-in.local.spec.ts against `next dev` on localhost:3100
//
// Nothing here touches production: the env contains only dummy/local values,
// Discord/Google/Blob credentials are unset, Google ADC is disabled, and
// e2e/local/preload.cjs blocks Discord and every external non-GET request.
//
// Options (env):
//   E2E_PORT=3100          app port
//   E2E_PG_PORT=54329      host port for the docker Postgres
//   E2E_DATABASE_URL=...   use an existing local Postgres instead of docker
//                          (host must be localhost; needs "password" auth)
//   E2E_KEEP_DB=1          leave the Postgres container running afterwards
//   E2E_SHOTS_DIR=...      where screenshots go (default e2e/.local/shots)
// Extra CLI args are passed to `playwright test` (e.g. --headed, -g celebration).
// `--serve` skips Playwright and just runs the seeded dev server for manual poking.
import { spawnSync, spawn } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const LOCAL_DIR = resolve(ROOT, "e2e/.local");
const MARKER = "# e2e:local";
const CONTAINER = "pizzadao-e2e-pg";
const PORT = process.env.E2E_PORT || "3100";
const PG_PORT = process.env.E2E_PG_PORT || "54329";

function log(msg) {
  console.log(`[e2e:local] ${msg}`);
}
function die(msg) {
  console.error(`[e2e:local] ERROR: ${msg}`);
  process.exit(1);
}
function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { cwd: ROOT, stdio: "inherit", ...opts });
  if (r.status !== 0) die(`${cmd} ${args.join(" ")} failed (exit ${r.status})`);
  return r;
}

// --- 1. Refuse to run next to real env files --------------------------------
// next dev loads .env* files; a developer's real .env.local could carry
// production DATABASE_URL / tokens into this run. Only our own generated file
// (first line = MARKER) is allowed.
for (const f of [".env", ".env.local", ".env.development", ".env.development.local"]) {
  const p = resolve(ROOT, f);
  if (existsSync(p) && !readFileSync(p, "utf8").startsWith(MARKER)) {
    die(`${f} exists and was not generated by e2e:local. Move it aside (or run from a clean worktree) so no real secrets leak into the local test run.`);
  }
}

// --- 2. Database -------------------------------------------------------------
let databaseUrl = process.env.E2E_DATABASE_URL;
let startedContainer = false;
let pgHost = "127.0.0.1";
let pgPort = PG_PORT;

if (databaseUrl) {
  const u = new URL(databaseUrl);
  if (!["localhost", "127.0.0.1"].includes(u.hostname)) die("E2E_DATABASE_URL must point at localhost");
  pgPort = u.port || "5432";
  u.hostname = "localhost";
  databaseUrl = u.toString();
} else {
  if (spawnSync("docker", ["info"], { stdio: "ignore" }).status !== 0) {
    die("docker is not available. Start Docker, or set E2E_DATABASE_URL to a local Postgres (password auth).");
  }
  spawnSync("docker", ["rm", "-f", CONTAINER], { stdio: "ignore" });
  log(`starting throwaway Postgres (${CONTAINER}) on 127.0.0.1:${PG_PORT}`);
  run("docker", [
    "run", "-d", "--rm", "--name", CONTAINER,
    "-e", "POSTGRES_USER=e2e", "-e", "POSTGRES_PASSWORD=e2e", "-e", "POSTGRES_DB=pizzadao_e2e",
    // Cleartext password auth: the Neon driver pipelines the password message.
    "-e", "POSTGRES_HOST_AUTH_METHOD=password",
    "-p", `127.0.0.1:${PG_PORT}:5432`,
    "--tmpfs", "/var/lib/postgresql/data",
    "postgres:17",
  ], { stdio: ["ignore", "ignore", "inherit"] });
  startedContainer = true;
  databaseUrl = `postgresql://e2e:e2e@localhost:${PG_PORT}/pizzadao_e2e`;
  let ready = false;
  for (let i = 0; i < 60 && !ready; i++) {
    ready = spawnSync("docker", ["exec", CONTAINER, "pg_isready", "-U", "e2e", "-h", "127.0.0.1"], { stdio: "ignore" }).status === 0;
    if (!ready) spawnSync("sleep", ["1"]);
  }
  if (!ready) die("Postgres did not become ready");
}

function cleanup() {
  if (startedContainer && !process.env.E2E_KEEP_DB) {
    spawnSync("docker", ["rm", "-f", CONTAINER], { stdio: "ignore" });
    startedContainer = false;
  }
}
process.on("exit", cleanup);
for (const sig of ["SIGINT", "SIGTERM"]) process.on(sig, () => { cleanup(); process.exit(130); });

// --- 3. Env (dummy + local values only) --------------------------------------
const sessionSecret = randomBytes(32).toString("hex");
const gcloudDir = resolve(tmpdir(), "pizzadao-e2e-empty-gcloud");
mkdirSync(gcloudDir, { recursive: true });
mkdirSync(LOCAL_DIR, { recursive: true });
const blockedLog = resolve(LOCAL_DIR, "blocked-requests.log");
rmSync(blockedLog, { force: true });

const fileEnv = {
  SESSION_SECRET: sessionSecret,
  DATABASE_URL: databaseUrl,
  // Served by e2e/local/preload.cjs: real public members sheet + synthetic test rows.
  MEMBERS_SHEET_ID: "e2e-local-members",
  DISCORD_CLIENT_ID: "e2e-fake-discord-client-id",
  DISCORD_REDIRECT_URI: `http://localhost:${PORT}/api/discord/callback`,
  NEXT_PUBLIC_BASE_URL: `http://localhost:${PORT}`,
};
writeFileSync(
  resolve(ROOT, ".env.local"),
  `${MARKER} — generated by e2e/local/run.mjs. Dummy/local values only; safe to delete.\n` +
    Object.entries(fileEnv).map(([k, v]) => `${k}=${v}`).join("\n") + "\n",
);

const env = {
  ...process.env,
  ...fileEnv,
  // Make sure nothing real leaks in from the shell.
  DISCORD_BOT_TOKEN: "",
  DISCORD_CLIENT_SECRET: "",
  DISCORD_GUILD_ID: "",
  GOOGLE_SERVICE_ACCOUNT_JSON: "",
  GOOGLE_SHEETS_WEBAPP_URL: "",
  GOOGLE_SHEETS_SHARED_SECRET: "",
  ANNOUNCE_WEBAPP_URL: "",
  ANNOUNCE_PASSWORD: "",
  BLOB_READ_WRITE_TOKEN: "",
  KV_REST_API_URL: "",
  KV_REST_API_TOKEN: "",
  X_CLIENT_ID: "",
  X_CLIENT_SECRET: "",
  CRON_SECRET: "",
  GITHUB_TOKEN: "",
  // Disable Google Application Default Credentials (gcloud user creds / metadata server).
  GOOGLE_APPLICATION_CREDENTIALS: resolve(gcloudDir, "does-not-exist.json"),
  CLOUDSDK_CONFIG: gcloudDir,
  METADATA_SERVER_DETECTION: "none",
  NO_GCE_CHECK: "true",
  // Local Postgres shim + network guard.
  NODE_OPTIONS: `${process.env.NODE_OPTIONS || ""} --require ${resolve(ROOT, "e2e/local/preload.cjs")}`.trim(),
  E2E_PG_HOST: pgHost,
  E2E_PG_PORT: pgPort,
  E2E_BLOCKED_LOG: blockedLog,
  E2E_PORT: PORT,
  E2E_SESSIONS_FILE: resolve(LOCAL_DIR, "sessions.json"),
  E2E_SHOTS_DIR: process.env.E2E_SHOTS_DIR || resolve(LOCAL_DIR, "shots"),
  NEXT_TELEMETRY_DISABLED: "1",
};

// --- 4. Schema + seed + cookies ----------------------------------------------
// NOTE: `prisma migrate deploy` cannot build this schema from an empty DB (the
// migration history predates several tables, e.g. "Bounty"), so the throwaway
// DB is created straight from schema.prisma.
log("creating schema (prisma db push)");
run("npx", ["prisma", "db", "push"], { env: { ...env, NODE_OPTIONS: "" } });
log("seeding test members");
run("node", ["e2e/local/seed.mjs"], { env });
log("minting session cookies");
run("node", ["--no-warnings", "e2e/local/mint-session.mjs", env.E2E_SESSIONS_FILE], { env: { ...env, NODE_OPTIONS: "" } });

// --- 5. Playwright (or just serve with --serve) ------------------------------
const serveOnly = process.argv.includes("--serve");
const child = serveOnly
  ? ["npx", ["next", "dev", "-p", PORT]]
  : ["npx", ["playwright", "test", "-c", "e2e/playwright.local.config.ts", ...process.argv.slice(2)]];
if (serveOnly) {
  log(`serving on http://localhost:${PORT} — session cookies in ${env.E2E_SESSIONS_FILE}. Ctrl+C to stop.`);
} else {
  log(`running Playwright against http://localhost:${PORT}`);
}
const pw = spawn(child[0], child[1], {
  cwd: ROOT,
  stdio: "inherit",
  env,
});
pw.on("exit", (code) => {
  if (existsSync(blockedLog)) {
    log(`external calls blocked by the network guard (see ${blockedLog}):`);
    process.stdout.write(readFileSync(blockedLog, "utf8"));
  } else {
    log("no external calls were blocked");
  }
  cleanup();
  process.exit(code ?? 1);
});
